### ISSUE TITLE
[AVM Module Issue]:

### ISSUE THREAD

**Issue by ajeetchouksey** [Azure/terraform-azurerm-avm-res-resources-resourcegroup#77]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.1.0

### Description

Please add location in resource group output.tf

**Comment by JFolberth** [comment]
@ajeetchouksey  thank you for opening this. Unfortunately I am going to close this and not merge the PR as per spec documentation "Remember, you SHOULD NOT output values that are already inputs (other than name)": https://azure.github.io/Azure-Verified-Modules/specs/tf/res/#id-tffr2---category-outputs---additional-terraform-outputs
